import { Montserrat } from "next/font/google";
import "./globals.css";

import { UserProvider } from "../components/UserContext";

const montserrat = Montserrat({
	weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
	subsets: ["latin"],
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang='it'>
			<UserProvider>
				<body className={montserrat.className}>{children}</body>
			</UserProvider>
		</html>
	);
}
